# For a full reference, see:
# https://skyline-docs.staging-ezcater.net/configuration/service_yml

name: gemstash
owner: tjwp
class: prototype
configuration_opt_in_environments: true
skip_production_deploy: true
pipeline:
  sandbox_cd_branch: master
experimental:
  docker:
    buildkit: false
staging:
  environment:
    RACK_ENV: staging
    RAILS_ENV: staging
production:
  environment:
    RACK_ENV: production
    RAILS_ENV: production
deployables:
  web:
    type: web
    port: 3000
    command: /entrypoint.sh gemstash start --config-file=/etc/gemstash/config.yml --no-daemonize
    health_check_path: /health
    staging:
      host: gemstash.staging-ezcater.net
      replicas: 2
    production:
      host: gemstash.ezcater.net
      replicas: 3
regions:
- us-east-1
slack: pb-a-gemstash
